import type { Skill } from './types'

export const skills = [
  { name: 'Python', level: 'Core' },
  { name: 'REST APIs' },
  { name: 'Flask' },
  { name: 'FastAPI' },
  { name: 'NumPy' },
  { name: 'Pandas' },
  { name: 'Data Cleaning' },
  { name: 'Data Preprocessing' },
  { name: 'Data Analysis' },
  { name: 'Exploratory Data Analysis (EDA)' },
  { name: 'Data Visualization' },
  { name: 'Matplotlib' },
  { name: 'Seaborn' },
  { name: 'SQL' },
  { name: 'MySQL' },
  { name: 'MongoDB' },
  { name: 'Excel' },
  { name: 'Generative AI' },
  { name: 'Large Language Models (LLMs)' },
  { name: 'OpenAI API' },
  { name: 'Prompt Engineering' },
  { name: 'LangChain' },
  { name: 'RAG (Retrieval Augmented Generation)' },
  { name: 'NLP (Natural Language Processing)' },
  { name: 'AI Integration with Python' },
  { name: 'Model Evaluation' },
  { name: 'AI Automation' },
  { name: 'Git' },
  { name: 'GitHub' },
  { name: 'API Integration' },
  { name: 'Automation' },
  { name: 'Express.js' },
  { name: 'React.js' },
  { name: 'Node.js', level: 'Proficient' },
  { name: 'JavaScript' },
  { name: 'TypeScript', level: 'Core' },
  { name: 'HTML' },
  { name: 'CSS' },
  { name: 'Tailwind CSS' },
  { name: 'Bootstrap' },
  { name: 'JWT Authentication' },
  { name: 'Full Stack Development' },
  { name: 'CRUD Applications' },
  { name: 'Responsive Web Design' },
] satisfies Skill[]
